name: create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: "dump github conext"
        run: echo '${{ toJSON( github.event ) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ ( github.event.issue.number ) }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  comment-with-api:
    runs-on: windows-latest
    steps:
      - name: Create comment with API
        run:
          gh apo -x POST \
          https://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER/comments \
          -f body = '
          Comment but from the API not action
          '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organisation.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE.NUMBER: ${{ github.event.issue.number }}
