name: Test Code Pull Requested

on: 
  pull_request:
    paths:
      - '**.html'
      - '**.htm'

jobs:
  test_pull_request:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: download npm
        run: npm ci
      - name: run html tests
        run: npm run htmlvalidate